# Generated by Django 4.0.3 on 2022-04-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ultimo_ingreso',
        ),
    ]
