# Generated by Django 4.0.3 on 2022-04-14 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_usuario', '0002_remove_usuario_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'Usuarios'},
        ),
    ]
