# Generated by Django 4.0.4 on 2022-04-23 22:49

import cuenta_usuario.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_usuario', '0006_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[cuenta_usuario.validators.UsernameValidator()]),
        ),
    ]
