# Generated by Django 4.0.4 on 2022-04-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_usuario', '0007_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(db_index=True, max_length=200, unique=True, verbose_name='correo electrónico'),
        ),
    ]
