# Generated by Django 4.0.5 on 2022-06-09 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_usuario', '0008_alter_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='es_activo',
        ),
    ]
