# Generated by Django 4.0.3 on 2022-04-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='ciudad',
            field=models.CharField(max_length=200, verbose_name='ciudad'),
        ),
    ]
