# Generated by Django 4.0.3 on 2022-04-15 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0002_alter_despacho_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region', models.CharField(choices=[('1', 'Region de Tarapacá'), ('2', 'Region de Antofagasta'), ('3', 'Region de Atacama'), ('4', 'Region de Coquimbo'), ('5', 'Region de Valparaíso'), ('6', 'Región del Libertador General Bernardo O’Higgins'), ('7', 'Región del Maule'), ('8', 'Región del Biobío'), ('9', 'Región de la Araucanía'), ('10', 'Región de los Lagos'), ('11', 'Región Aysén del General Carlos Ibáñez del Campo'), ('12', 'Región de Magallanes y de la Antártica Chilena'), ('13', 'Región Metropolitana de Santiago'), ('14', 'Región de los Ríos'), ('15', 'Región de Arica y Parinacota'), ('16', 'Región de Ñuble')], max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cuidad',
            fields=[
                ('nombre', models.CharField(choices=[('1', 'Puente Alto'), ('2', 'Maipú'), ('3', 'Santiago'), ('4', 'La Florida'), ('5', 'Temuco'), ('6', 'Antofagasta'), ('7', 'Vina del Mar'), ('8', 'San Bernardo'), ('9', 'Valparaíso'), ('10', 'Las Condes'), ('11', 'Peñalolén'), ('12', 'Rancagua'), ('13', 'Arica'), ('14', 'Concepción'), ('15', 'Quilicura'), ('16', 'ÑUÑOA'), ('17', 'Talca'), ('18', 'Pudahuel'), ('19', 'La Serena'), ('20', 'Iquique'), ('21', 'La Pintana'), ('22', 'Puerto Montt'), ('23', 'Chillán'), ('24', 'El Bosque'), ('25', 'Calama'), ('26', 'Recoleta'), ('27', 'Copiapó'), ('28', 'Valdivia'), ('29', 'Quilpué'), ('30', 'Talcahuano'), ('31', 'Osorno'), ('32', 'Renca'), ('33', 'Los Ángeles'), ('34', 'Providencia'), ('35', 'Estación Central'), ('36', 'Cerro Navia'), ('37', 'San Pedro de la Paz'), ('38', 'Conchalí'), ('39', 'Curicó'), ('40', 'Villa Alemana'), ('41', 'Punta Arenas'), ('42', 'La Granja'), ('43', 'Macul'), ('44', 'Coronel'), ('45', 'Quinta Normal'), ('46', 'San Miguel'), ('47', 'Alto Hospicio'), ('48', 'Lo Barnechea'), ('49', 'Pedro Aguirre Cerda'), ('50', 'Independencia'), ('51', 'Lo Espejo'), ('52', 'Huechuraba'), ('53', 'Lo prado'), ('54', 'San Joaquín'), ('55', 'La Reina'), ('56', 'Hualpén'), ('57', 'La Cisterna'), ('58', 'La Colina'), ('59', 'San Antonio'), ('60', 'Chiguayante'), ('61', 'Vitacura'), ('62', 'Peñaflor'), ('63', 'San Ramón'), ('64', 'Cerrillos'), ('65', 'Ovalle'), ('66', 'Linaríes')], max_length=100, primary_key=True, serialize=False)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despacho.region')),
            ],
        ),
        migrations.AlterField(
            model_name='despacho',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='despacho.cuidad', verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despacho.region', verbose_name='region'),
        ),
    ]
