# Generated by Django 4.0.3 on 2022-04-15 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0003_region_cuidad_alter_despacho_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidad',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='despacho.region'),
        ),
    ]
