# Generated by Django 4.0.3 on 2022-04-15 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0004_alter_cuidad_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='region',
            new_name='nombre',
        ),
    ]
