# Generated by Django 4.0.3 on 2022-04-15 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0005_rename_region_region_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuidad',
            new_name='Ciudad',
        ),
    ]
