# Generated by Django 4.0.3 on 2022-04-16 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0006_rename_cuidad_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegionChile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='despacho',
            name='ciudad',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.AddField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='despacho.regionchile'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despacho.regionchile', verbose_name='region'),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
