# Generated by Django 4.0.3 on 2022-04-16 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0007_provincia_regionchile_remove_despacho_ciudad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('1', 'Region de Tarapacá'), ('2', 'Region de Antofagasta'), ('3', 'Region de Atacama'), ('4', 'Region de Coquimbo'), ('5', 'Region de Valparaíso'), ('6', 'Región del Libertador General Bernardo O’Higgins'), ('7', 'Región del Maule'), ('8', 'Región del Biobío'), ('9', 'Región de la Araucanía'), ('10', 'Región de los Lagos'), ('11', 'Región Aysén del General Carlos Ibáñez del Campo'), ('12', 'Región de Magallanes y de la Antártica Chilena'), ('13', 'Región Metropolitana de Santiago'), ('14', 'Región de los Ríos'), ('15', 'Región de Arica y Parinacota'), ('16', 'Región de Ñuble')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='despacho',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despacho.region', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='despacho.region'),
        ),
        migrations.DeleteModel(
            name='RegionChile',
        ),
    ]
