# Generated by Django 4.0.3 on 2022-04-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0010_remove_despacho_calle_remove_despacho_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='error',
            field=models.BooleanField(default=False),
        ),
    ]
