# Generated by Django 4.0.3 on 2022-04-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0011_comuna_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='error',
        ),
    ]
