# Generated by Django 4.0.3 on 2022-04-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0012_remove_comuna_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despacho',
            name='region',
        ),
    ]
