# Generated by Django 4.0.3 on 2022-04-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0013_remove_despacho_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
