# Generated by Django 4.0.3 on 2022-04-16 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('despacho', '0014_alter_region_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despacho.direccion', verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
