# Generated by Django 4.0.3 on 2022-04-17 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0015_alter_despacho_direccion_alter_despacho_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='telefono',
            field=models.CharField(default='+569123456789', max_length=12, validators=[django.core.validators.RegexValidator(code='invalid_celular', message='El celular debe seguir el siguiente formato: +569123456789', regex='^(\\+?56)?(\\s?)(0?9)(\\s?)[9876543]\\d{7}$')], verbose_name='telefono'),
        ),
    ]
