# Generated by Django 4.0.3 on 2022-04-17 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0016_alter_direccion_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='codigo_postal',
            field=models.IntegerField(max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_codigo_postal', message='El codigo postal debe tener 7 digitos. Ej: 1234567', regex='^[0-9]{7}$')], verbose_name='codigo postal'),
        ),
    ]
