# Generated by Django 4.0.3 on 2022-04-17 23:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0019_alter_direccion_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despacho',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='despacho',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='despacho.direccion', verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='telefono',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(code='invalid_celular', message='El celular debe seguir el siguiente formato: +569123456789', regex='^(\\+?56)?(\\s?)(0?9)(\\s?)[9876543]\\d{7}$')], verbose_name='telefono'),
        ),
    ]
