# Generated by Django 4.0.3 on 2022-04-17 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despacho', '0020_remove_despacho_usuario_alter_despacho_direccion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'verbose_name_plural': 'Direcciones'},
        ),
    ]
