# Generated by Django 4.0.3 on 2022-04-11 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('despacho', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('fecha_venta', models.DateField(verbose_name='fecha venta')),
                ('estado', models.PositiveSmallIntegerField(choices=[[1, 'Pendiente'], [2, 'Cancelada'], [3, 'Finalizada']], default=1)),
                ('despacho', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='despacho.despacho')),
                ('productos', models.ManyToManyField(to='inventario.producto')),
            ],
        ),
    ]
