# Generated by Django 4.0.4 on 2022-05-04 02:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0007_producto_es_nuevo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.PositiveSmallIntegerField(choices=[[1, 'Pendiente'], [2, 'En_proceso'], [3, 'Finalizado'], [4, 'Fallido']], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('fecha_venta', models.DateField(null=True, verbose_name='fecha venta')),
                ('estado', models.PositiveSmallIntegerField(choices=[[1, 'Pendiente'], [2, 'Cancelada'], [3, 'Aprobada']], default=1)),
                ('imagen_deposito', models.ImageField(upload_to='comprobantes/')),
                ('despacho', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='venta.despacho')),
            ],
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.venta')),
            ],
            options={
                'verbose_name': 'Productos de la venta',
                'verbose_name_plural': 'Productos de la venta',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='venta.region')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('departamento', models.CharField(blank=True, max_length=200, verbose_name='departamento')),
                ('piso', models.CharField(blank=True, max_length=200, null=True, verbose_name='piso')),
                ('codigo_postal', models.IntegerField(validators=[django.core.validators.RegexValidator(code='invalid_codigo_postal', message='El codigo postal debe tener 7 digitos. Ej: 1234567', regex='^[0-9]{7}$')], verbose_name='codigo postal')),
                ('telefono', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(code='invalid_celular', message='El celular debe seguir el siguiente formato: +569123456789', regex='^(\\+?56)?(\\s?)(0?9)(\\s?)[9876543]\\d{7}$')], verbose_name='telefono')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='venta.comuna')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.AddField(
            model_name='despacho',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.direccion', verbose_name='dirección'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='venta.provincia'),
        ),
    ]
