# Generated by Django 4.0.4 on 2022-05-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='imagen_deposito',
            field=models.ImageField(default='templates/static/img/holder.jpg', upload_to='comprobantes/'),
        ),
    ]
