# Generated by Django 4.0.4 on 2022-05-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_alter_venta_imagen_deposito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='imagen_deposito',
            field=models.ImageField(default='comprobantes/holder.jpg', upload_to='comprobantes/'),
        ),
    ]
