# Generated by Django 4.0.4 on 2022-05-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_venta_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, max_length=100, verbose_name='codigo de seguimiento Starken'),
        ),
    ]
