# Generated by Django 4.0.4 on 2022-05-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_venta_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, max_length=100, verbose_name='codigo de seguimiento Starken'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='boleta',
            field=models.FileField(null=True, upload_to='boletas/'),
        ),
    ]
