# Generated by Django 4.0.3 on 2022-04-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_remove_venta_productos_ventaproducto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventaproducto',
            options={'verbose_name': 'Productos de la venta', 'verbose_name_plural': 'Productos de la venta'},
        ),
    ]
