# Generated by Django 4.0.4 on 2022-05-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_alter_ventaproducto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='imagen_deposito',
            field=models.ImageField(blank=True, null=True, upload_to='venta/'),
        ),
    ]
