# Generated by Django 4.0.4 on 2022-05-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_comprobantetemporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.IntegerField(verbose_name='total'),
        ),
    ]
