# Generated by Django 4.0.4 on 2022-05-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_venta_imagen_deposito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(verbose_name='fecha venta'),
        ),
    ]
