# Generated by Django 4.0.4 on 2022-05-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_alter_venta_fecha_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[[1, 'Pendiente'], [2, 'Cancelada'], [3, 'Aprobada']], default=1),
        ),
        migrations.AlterField(
            model_name='venta',
            name='imagen_deposito',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
    ]
