# Generated by Django 4.0.3 on 2022-04-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editorial',
            old_name='editorial',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='otros_autores',
        ),
        migrations.AddField(
            model_name='producto',
            name='otros_autores',
            field=models.ManyToManyField(blank=True, to='inventario.otrosautores', verbose_name='otros autores'),
        ),
    ]
