# Generated by Django 4.0.3 on 2022-04-11 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_editorial_editorial_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pais',
            old_name='pais',
            new_name='nombre',
        ),
    ]
