# Generated by Django 4.0.3 on 2022-04-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_autor_options_alter_editorial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='portada',
            field=models.ImageField(blank=True, upload_to='portadas', verbose_name='portada'),
        ),
    ]
