# Generated by Django 4.0.3 on 2022-04-15 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_autor_options_alter_editorial_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='iva',
        ),
        migrations.DeleteModel(
            name='IVA',
        ),
    ]
