# Generated by Django 4.0.3 on 2022-04-16 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_producto_portada'),
        ('inventario', '0005_remove_producto_iva_delete_iva'),
    ]

    operations = [
    ]
