# Generated by Django 4.0.4 on 2022-05-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'Género'},
        ),
        migrations.AlterModelOptions(
            name='otrosautores',
            options={'verbose_name_plural': 'Otros Autores'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(max_length=200, unique=True, verbose_name='género'),
        ),
    ]
