# Generated by Django 4.0.5 on 2022-06-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_genero_options_alter_otrosautores_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='numero_paginas',
            field=models.PositiveIntegerField(verbose_name='numero de paginas'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='stock'),
        ),
    ]
