# Generated by Django 4.0.3 on 2022-04-09 01:32

import contacto.tipo_enum.tipo_ticket
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(verbose_name='fecha de creacion')),
                ('mensaje', models.CharField(max_length=200, verbose_name='mensaje')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(verbose_name='fecha de creacion')),
                ('respuesta', models.CharField(max_length=200, verbose_name='respuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.PositiveSmallIntegerField(choices=[[1, 'Duda'], [2, 'Sugerencia'], [3, 'Queja']], default=contacto.tipo_enum.tipo_ticket.TipoTicket['SUGERENCIA'])),
                ('fecha_creacion', models.DateTimeField(verbose_name='fecha de creacion')),
                ('fecha_modificacion', models.DateTimeField(verbose_name='fecha de modificacion')),
                ('estado', models.PositiveSmallIntegerField(choices=[[1, 'Pendiente'], [2, 'Resuelto'], [3, 'Cancelado']], default=1)),
            ],
        ),
    ]
