# Generated by Django 4.0.5 on 2022-06-07 21:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0003_ticket_cantidad_mensajes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='texto',
            field=ckeditor.fields.RichTextField(verbose_name='texto'),
        ),
    ]
