# Generated by Django 4.0.4 on 2022-05-26 23:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0010_alter_genero_options_alter_otrosautores_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la campaña. Útil para encontrarla más fácilmente en el menú de administración.', max_length=100, verbose_name='Nombre')),
                ('estado', models.PositiveIntegerField(choices=[[1, 'DRAFT'], [2, 'PUBLICADA'], [3, 'INACTIVA']], default=1, help_text='Estado de una campaña. Determina su visibilidad en el banner de la página principal', verbose_name='Estado')),
                ('auto_expira', models.BooleanField(default=False, help_text='Si se activa, la campaña se expira automáticamente cuando la fecha de expiración se haya alcanzado.', verbose_name='Auto expira')),
                ('fecha_expiracion', models.DateField(default=datetime.date(2022, 6, 25), help_text='Si auto expiración está activa, la campaña pasará a inactiva una vez alcanzada esta fecha, de otro modo no tiene efecto.', verbose_name='Fecha expiración')),
                ('redirige_a', models.PositiveIntegerField(choices=[[1, 'PRODUCTO'], [2, 'GENERO'], [3, 'EDITORIAL'], [4, 'AUTOR'], [5, 'OTRO']], default=1, help_text='Determina a qué se redirige al hacer click en la campaña. La forma en que se resuelva la URL dependerá de este campo.', verbose_name='Redirige a')),
                ('key_url', models.CharField(help_text='Dependiendo del tipo de redirección, esta llave puede ser una ID de un objeto de la base de datos o una URL entera en caso de elegir "OTRO".', max_length=100, verbose_name='Llave URL')),
                ('imagen', models.ImageField(help_text='Imagen que se mostrará en el banner de la página principal.', upload_to='campañas', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.IntegerField(default=10, verbose_name='descuento')),
                ('fecha_inicio', models.DateField(verbose_name='fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha fin')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
    ]
