# Generated by Django 4.0.3 on 2022-04-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descuento', models.IntegerField(default=10, verbose_name='descuento')),
                ('fecha_inicio', models.DateField(verbose_name='fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha fin')),
                ('es_activa', models.BooleanField(default=True)),
            ],
        ),
    ]
