# Generated by Django 4.0.3 on 2022-04-11 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventario.producto')),
                ('descuento', models.IntegerField(default=10, verbose_name='descuento')),
                ('fecha_inicio', models.DateField(verbose_name='fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha fin')),
            ],
        ),
    ]
