# Generated by Django 4.0.5 on 2022-06-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='descuento',
            field=models.PositiveIntegerField(default=10, verbose_name='descuento'),
        ),
    ]
