# Generated by Django 4.0.5 on 2022-06-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_campanna_fecha_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanna',
            name='fecha_expiracion',
            field=models.DateField(blank=True, help_text='Si auto expiración está activa, la campaña pasará a inactiva una vez alcanzada esta fecha, de otro modo no tiene efecto.', null=True, verbose_name='Fecha expiración'),
        ),
    ]
