# Generated by Django 4.0.4 on 2022-05-14 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_campanna_fecha_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanna',
            name='fecha_expiracion',
            field=models.DateField(default=datetime.date(2022, 6, 13), help_text='Si auto expiración está activa, la campaña pasará a inactiva una vez alcanzada esta fecha, de otro modo no tiene efecto.', verbose_name='Fecha expiración'),
        ),
    ]
