# [`provincia_id`,`provincia_nombre`,`region_id]
arica = [1, 'arica', 1]
parinacota = [2, 'parinacota', 1]
iquique = [3, 'iquique', 2]
tamarugal = [4, 'el tamarugal', 2]
antofagasta = [5, 'antofagasta', 3]
loa = [6, 'el loa', 3]
tocopilla = [7, 'tocopilla', 3]
chanaral = [8, 'chañaral', 4]
copiapo = [9, 'copiapó', 4]
hausco = [10, 'huasco', 4]
choapa = [11, 'choapa', 5]
elqui = [12, 'elqui', 5]
limari = [13, 'limarí', 5]
pascua = [14, 'isla de pascua', 6]
andes = [15, 'los andes', 6]
petorca = [16, 'petorca', 6]
quillota = [17, 'quillota', 6]
antonio = [18, 'san antonio', 6]
felipe = [19, 'san felipe de aconcagua', 6]
valparaiso = [20, 'valparaiso', 6]
chacabuco = [21, 'chacabuco', 7]
cordillera = [22, 'cordillera', 7]
maipo = [23, 'maipo', 7]
melipilla = [24, 'melipilla', 7]
santiago = [25, 'santiago', 7]
talagante = [26, 'talagante', 7]
cachapoal = [27, 'cachapoal', 8]
cardenal = [28, 'cardenal caro', 8]
colchagua = [29, 'colchagua', 8]
cauquenes = [30, 'cauquenes', 9]
curico = [31, 'curicó', 9]
linares = [32, 'linares', 9]
talca = [33, 'talca', 9]
arauco = [34, 'arauco', 10]
biobio = [35, 'bio bío', 10]
concepcion = [36, 'concepción', 10]
nuble = [37, 'ñuble', 10]
cautin = [38, 'cautín', 11]
malleco = [39, 'malleco', 11]
valdivia = [40, 'valdivia', 12]
ranco = [41, 'ranco', 12]
chiloe = [42, 'chiloé', 13]
llanquihue = [43, 'llanquihue', 13]
osorno = [44, 'osorno', 13]
palena = [45, 'palena', 13]
aisen = [46, 'aisén', 14]
prat = [47, 'capitán prat', 14]
coihaique = [48, 'coihaique', 14]
general = [49, 'general carrera', 14]
antartica = [50, 'antártica chilena', 15]
magallanes = [51, 'magallanes', 15]
fuego = [52, 'tierra del fuego', 15]
esperanza = [53, 'última esperanza', 1]

provincia = [arica, parinacota, iquique, tamarugal, antofagasta, loa, tocopilla, chanaral, copiapo, hausco, choapa,
             elqui, limari, pascua, andes, petorca, quillota, antonio, felipe, valparaiso, chacabuco, cordillera, maipo,
             melipilla, santiago, talagante, cachapoal, cardenal, colchagua, cauquenes, curico, linares, talca, arauco,
             biobio, concepcion, nuble, cautin, malleco, valdivia, ranco, chiloe, llanquihue, osorno, palena, aisen,
             prat, coihaique, general, antartica, magallanes, fuego, esperanza]
