# Generated by Django 4.0.4 on 2022-05-17 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del reporte. El reporte puede ser compartido por varias iteraciones del mismo reporte y funciona como un identificador para agrupar los datos del mismo.', max_length=250, verbose_name='Nombre')),
                ('iteracion', models.IntegerField(blank=True, default=-1, help_text='Número de iteración del reporte. Sirve para identificar varios reportes con el mismo nombre', verbose_name='Iteración')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.JSONField(help_text='Datos de interés para la página. Los datos se guardan en formato JSON.', verbose_name='Datos')),
                ('chart_config', models.JSONField(help_text='Configuración del gráfico para la página. Los datos se guardan en formato JSON.', verbose_name='Configuración del gráfico')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analitica.reporte')),
            ],
        ),
    ]
